import type { Metadata } from "next";
import { Chakra_Petch, Poppins, Source_Code_Pro } from "next/font/google";
import "./globals.css";
import { CartProvider } from "@/components/cart/cart-context";
import { NavBar } from "@/components/layout/navbar";
import { cookies } from "next/headers";
import { getCart } from "@/lib/shopify";


const chakraPetch = Chakra_Petch({
  weight: "600",
  variable: "--font-chakra",
  subsets: ["latin"],
});

const sourceCode = Source_Code_Pro({
  weight: "400",
  variable: "--font-sourceCode",
  subsets: ["latin"],
});

const poppins = Poppins({
  weight: "600",
  variable: "--font-poppins",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cartId = (await cookies()).get("cartId")?.value;
  const cart = getCart(cartId);
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${sourceCode.variable} ${chakraPetch.variable} antialiased bg-gray-100`}
      >
        <CartProvider cartPromise={cart}>
          <NavBar />
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
